import * as ROT from 'rot-js';

ROT.RNG.setSeed(100);
ROT.Display.Rect.cache = true;

export default {
  debug: {
    showInvisibleEnemies: false,
    invisibleEnemiesFgColor: '#AA9F9D',
    showEnemyFov: false,
    enemyFovBgColor: '#AA9F9D',
    showEnemyCoverMap: false,
    enemyCoverMapBgColor: '#AA5555'
  },
  width: 126,
  height: 38,
  overworldWidth: 126,
  overworldHeight: 24,
  localWidth: 100,
  localHeight: 24,
  contextCommandsHeight: 3,
  fontSize: 16,
  displaySpacing: 1.0,
  displayBorder: 0.0,
  rng: ROT.RNG,
  keyMap: {
    [ROT.KEYS.VK_LEFT]: 'LEFT',
    [ROT.KEYS.VK_RIGHT]: 'RIGHT',
    [ROT.KEYS.VK_UP]: 'UP',
    [ROT.KEYS.VK_DOWN]: 'DOWN',
    [ROT.KEYS.VK_RETURN]: 'ENTER',
    [ROT.KEYS.VK_Z]: 'WAIT',
    [ROT.KEYS.VK_A]: 'ATTACK',
    [ROT.KEYS.VK_S]: 'NEXT TARGET',
    [ROT.KEYS.VK_D]: 'TOGGLE WEAPON',
    [ROT.KEYS.VK_P]: 'PRONE',
    [ROT.KEYS.VK_E]: 'ENTER/EXIT',
    [ROT.KEYS.VK_I]: 'INVENTORY',
    [ROT.KEYS.VK_T]: 'TAKE',
    [ROT.KEYS.VK_1]: 'NUM_1',
    [ROT.KEYS.VK_2]: 'NUM_2',
    [ROT.KEYS.VK_3]: 'NUM_3',
    [ROT.KEYS.VK_4]: 'NUM_4',
    [ROT.KEYS.VK_5]: 'NUM_5',
    [ROT.KEYS.VK_6]: 'NUM_6',
    [ROT.KEYS.VK_7]: 'NUM_7',
    [ROT.KEYS.VK_8]: 'NUM_8'
  },
  localMapNotVisibleBrightness: -75,
  overworldMapNotVisibleBrightness: -60,
  baseOverworldEnemyProb: 0.60,
  xOverworldEnemyProb: 0.75,
  southernOverworldEnemyHeight: 5,
  southernOverworldEnemyProb: 0.99,
  localStartingDepth: 50,
  lootDropsPerEnemyMember: 5,
  projectileIntervalMillis: 100,
  projectileRoundBreakFrames: 1,
  projectileBurstBreakFrames: 5,
  moveIntervalMillis: 400,
  maxInjuries: 2,
  hitCharacterPowerLoss: 40,
  fovConcealmentThreshold: 100,
  fovCoverThreshold: 75,
  animationIntervalMillis: 100,
  inGameStartDate: new Date(1967, 6, 3, 0)
};
